name : Run Test
on: 
  push:
    branches: [ main ]
    path-ignore:
      - 'github/workflows/**'
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning repository
      uses: actions/checkout@v6
    - name: Set up Node.js and cache node modules
      uses: ./.github/actions/setupnode
      with:
        node-version: '14'
    - name: Run tests
      run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Cloning repository
      uses: actions/checkout@v6
    - name: Set up Node.js and cache node modules
      uses: ./.github/actions/setupnode
      with:
        node-version: '14'
    - name: Build project
      run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Cloning repository
      uses: actions/checkout@v6
    - name: Deploy to GitHub Pages
      run: echo "Deploying to GitHub Pages..."

